# Generated by Django 6.0.2 on 2026-02-28 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0002_ad_category_post_delete_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='url',
        ),
        migrations.AddField(
            model_name='ad',
            name='link',
            field=models.URLField(blank=True, verbose_name='Сілтеме'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='image',
            field=models.ImageField(upload_to='ads/', verbose_name='Жарнама суреті'),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='core_app.category'),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to='news_images/', verbose_name='Сурет'),
        ),
    ]
