# Generated by Django 6.0.2 on 2026-02-21 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Student name')),
                ('group', models.CharField(max_length=58, verbose_name='Group name')),
                ('gpa', models.FloatField(verbose_name='GPA')),
                ('birthdate', models.DateField(verbose_name='Birthdte')),
            ],
        ),
    ]
