# Generated by Django 6.0.2 on 2026-02-28 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Жарнама атауы')),
                ('image', models.ImageField(upload_to='ads_images/', verbose_name='Жарнама суреті')),
                ('url', models.URLField(verbose_name='Сілтеме')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Санат атауы')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Тақырыбы')),
                ('content', models.TextField(verbose_name='Мәтіні')),
                ('image', models.ImageField(upload_to='news_images/', verbose_name='Суреті')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Жарияланған уақыты')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_app.category', verbose_name='Санаты')),
            ],
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
